name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false  # Важно для корректной работы с токенами

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Make gradlew executable
        run: chmod +x gradlew

      - uses: Xotabu4/selenoid-github-action@v2

      - name: Run tests
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # Добавляем токен

      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Используем правильный параметр
          publish_branch: gh-pages
          publish_dir: allure-history